export const CONSTITUENCY_TO_COUNTY: Record<string, string> = {
  // Mombasa
  Changamwe: "Mombasa",
  Jomvu: "Mombasa",
  Kisauni: "Mombasa",
  Nyali: "Mombasa",
  Likoni: "Mombasa",
  Mvita: "Mombasa",
  // Kwale
  Msambweni: "Kwale",
  "Lunga Lunga": "Kwale",
  Matuga: "Kwale",
  Kinango: "Kwale",
  // Kilifi
  "Kilifi North": "Kilifi",
  "Kilifi South": "Kilifi",
  Kaloleni: "Kilifi",
  Rabai: "Kilifi",
  Ganze: "Kilifi",
  Malindi: "Kilifi",
  Magarini: "Kilifi",
  // Tana River
  Garsen: "Tana River",
  Galole: "Tana River",
  Bura: "Tana River",
  // Lamu
  "Lamu East": "Lamu",
  "Lamu West": "Lamu",
  // Taita Taveta
  Taveta: "Taita Taveta",
  Wundanyi: "Taita Taveta",
  Mwatate: "Taita Taveta",
  Voi: "Taita Taveta",
  // Garissa
  "Garissa Township": "Garissa",
  Balambala: "Garissa",
  Lagdera: "Garissa",
  Dadaab: "Garissa",
  Fafi: "Garissa",
  Ijara: "Garissa",
  // Wajir
  "Wajir North": "Wajir",
  "Wajir East": "Wajir",
  Tarajia: "Wajir",
  "Wajir South": "Wajir",
  "Wajir West": "Wajir",
  Eldas: "Wajir",
  Tarbaj: "Wajir",
  // Mandera
  "Mandera West": "Mandera",
  Banisa: "Mandera",
  Banissa: "Mandera",
  "Mandera North": "Mandera",
  "Mandera East": "Mandera",
  Lafey: "Mandera",
  "Mandera South": "Mandera",
  // Marsabit
  Moyale: "Marsabit",
  "North Horr": "Marsabit",
  Saku: "Marsabit",
  Laisamis: "Marsabit",
  // Isiolo
  "Isiolo North": "Isiolo",
  "Isiolo South": "Isiolo",
  // Meru
  "Igembe South": "Meru",
  "Igembe Central": "Meru",
  "Igembe North": "Meru",
  "Tigania West": "Meru",
  "Tigania East": "Meru",
  "North Imenti": "Meru",
  Buuri: "Meru",
  "Central Imenti": "Meru",
  "South Imenti": "Meru",
  // Tharaka-Nithi
  Maara: "Tharaka-Nithi",
  "Chuka/Igambang'ombe": "Tharaka-Nithi",
  Tharaka: "Tharaka-Nithi",
  // Embu
  Manyatta: "Embu",
  Runyenjes: "Embu",
  "Mbeere North": "Embu",
  "Mbeere South": "Embu",
  // Kitui
  "Mwingi North": "Kitui",
  "Mwingi West": "Kitui",
  "Mwingi Central": "Kitui",
  "Kitui West": "Kitui",
  "Kitui Rural": "Kitui",
  "Kitui Central": "Kitui",
  "Kitui East": "Kitui",
  "Kitui South": "Kitui",
  // Machakos
  Masinga: "Machakos",
  Yatta: "Machakos",
  Kangundo: "Machakos",
  Matungulu: "Machakos",
  Kathiani: "Machakos",
  Mavoko: "Machakos",
  "Machakos Town": "Machakos",
  Mwala: "Machakos",
  // Makueni
  Mbooni: "Makueni",
  Kilome: "Makueni",
  Kaiti: "Makueni",
  Makueni: "Makueni",
  "Kibwezi West": "Makueni",
  "Kibwezi East": "Makueni",
  // Nyandarua
  Kinangop: "Nyandarua",
  Kipipiri: "Nyandarua",
  "Ol Kalou": "Nyandarua",
  "Ol Jorok": "Nyandarua",
  Ndaragwa: "Nyandarua",
  // Nyeri
  Tetu: "Nyeri",
  Kieni: "Nyeri",
  Mathira: "Nyeri",
  Othaya: "Nyeri",
  Mukurweini: "Nyeri",
  "Nyeri Town": "Nyeri",
  // Kirinyaga
  Mwea: "Kirinyaga",
  Gichugu: "Kirinyaga",
  Ndia: "Kirinyaga",
  "Kirinyaga Central": "Kirinyaga",
  // Murang'a
  Kangema: "Murang'a",
  Mathioya: "Murang'a",
  Kiharu: "Murang'a",
  Kigumo: "Murang'a",
  Kandara: "Murang'a",
  Gatanga: "Murang'a",
  Maragwa: "Murang'a",
  // Kiambu
  "Gatundu South": "Kiambu",
  "Gatundu North": "Kiambu",
  Juja: "Kiambu",
  "Thika Town": "Kiambu",
  Ruiru: "Kiambu",
  Githunguri: "Kiambu",
  Kiambu: "Kiambu",
  Kiambaa: "Kiambu",
  Kabete: "Kiambu",
  Kikuyu: "Kiambu",
  Limuru: "Kiambu",
  Lari: "Kiambu",
  // Turkana
  "Turkana North": "Turkana",
  "Turkana West": "Turkana",
  "Turkana Central": "Turkana",
  Loima: "Turkana",
  "Turkana South": "Turkana",
  "Turkana East": "Turkana",
  // West Pokot
  Kapenguria: "West Pokot",
  Sigor: "West Pokot",
  Kacheliba: "West Pokot",
  "Pokot South": "West Pokot",
  // Samburu
  "Samburu West": "Samburu",
  "Samburu North": "Samburu",
  "Samburu East": "Samburu",
  // Trans Nzoia
  Kwanza: "Trans Nzoia",
  Endebess: "Trans Nzoia",
  Saboti: "Trans Nzoia",
  Kiminini: "Trans Nzoia",
  Cherangany: "Trans Nzoia",
  // Uasin Gishu
  Soy: "Uasin Gishu",
  Turbo: "Uasin Gishu",
  Moiben: "Uasin Gishu",
  Ainabkoi: "Uasin Gishu",
  Kapseret: "Uasin Gishu",
  Kesses: "Uasin Gishu",
  // Elgeyo Marakwet
  "Marakwet East": "Elgeyo Marakwet",
  "Marakwet West": "Elgeyo Marakwet",
  "Keiyo North": "Elgeyo Marakwet",
  "Keiyo South": "Elgeyo Marakwet",
  // Nandi
  Tindiret: "Nandi",
  Tinderet: "Nandi",
  Aldai: "Nandi",
  "Nandi Hills": "Nandi",
  Chesumei: "Nandi",
  Emgwen: "Nandi",
  Mosop: "Nandi",
  // Baringo
  Tiaty: "Baringo",
  "Baringo North": "Baringo",
  "Baringo Central": "Baringo",
  "Baringo South": "Baringo",
  Mogotio: "Baringo",
  "Eldama Ravine": "Baringo",
  // Laikipia
  "Laikipia West": "Laikipia",
  "Laikipia East": "Laikipia",
  "Laikipia North": "Laikipia",
  // Nakuru
  Molo: "Nakuru",
  Njoro: "Nakuru",
  Naivasha: "Nakuru",
  Gilgil: "Nakuru",
  "Kuresoi South": "Nakuru",
  "Kuresoi North": "Nakuru",
  Subukia: "Nakuru",
  Rongai: "Nakuru",
  Bahati: "Nakuru",
  "Nakuru Town West": "Nakuru",
  "Nakuru Town East": "Nakuru",
  // Narok
  Kilgoris: "Narok",
  "Emurua Dikirr": "Narok",
  "Narok North": "Narok",
  "Narok East": "Narok",
  "Narok South": "Narok",
  "Narok West": "Narok",
  // Kajiado
  "Kajiado North": "Kajiado",
  "Kajiado Central": "Kajiado",
  "Kajiado East": "Kajiado",
  "Kajiado West": "Kajiado",
  "Kajiado South": "Kajiado",
  // Kericho
  "Kipkelion East": "Kericho",
  "Kipkelion West": "Kericho",
  Ainamoi: "Kericho",
  Bureti: "Kericho",
  Belgut: "Kericho",
  "Soin Sigowet": "Kericho",
  // Bomet
  Sotik: "Bomet",
  Chepalungu: "Bomet",
  "Bomet East": "Bomet",
  "Bomet Central": "Bomet",
  Konoin: "Bomet",
  // Kakamega
  Lugari: "Kakamega",
  Likuyani: "Kakamega",
  Malava: "Kakamega",
  Lurambi: "Kakamega",
  Navakholo: "Kakamega",
  "Mumias West": "Kakamega",
  "Mumias East": "Kakamega",
  Matungu: "Kakamega",
  Butere: "Kakamega",
  Khwisero: "Kakamega",
  Shinyalu: "Kakamega",
  Ikolomani: "Kakamega",
  // Vihiga
  Vihiga: "Vihiga",
  Sabatia: "Vihiga",
  Hamisi: "Vihiga",
  Luanda: "Vihiga",
  Emuhaya: "Vihiga",
  // Bungoma
  "Mt. Elgon": "Bungoma",
  Sirisia: "Bungoma",
  Kabuchai: "Bungoma",
  Bumula: "Bungoma",
  Kanduyi: "Bungoma",
  "Webuye East": "Bungoma",
  "Webuye West": "Bungoma",
  Kimilili: "Bungoma",
  Tongaren: "Bungoma",
  // Busia
  "Teso North": "Busia",
  "Teso South": "Busia",
  Nambale: "Busia",
  Matayos: "Busia",
  Butula: "Busia",
  Funyula: "Busia",
  Budalangi: "Busia",
  // Siaya
  Ugenya: "Siaya",
  Ugunja: "Siaya",
  "Alego Usonga": "Siaya",
  Gem: "Siaya",
  Bondo: "Siaya",
  Rarieda: "Siaya",
  // Kisumu
  "Kisumu East": "Kisumu",
  "Kisumu West": "Kisumu",
  "Kisumu Central": "Kisumu",
  Seme: "Kisumu",
  Nyando: "Kisumu",
  Muhoroni: "Kisumu",
  Nyakach: "Kisumu",
  // Homa Bay
  Kasipul: "Homa Bay",
  "Kabondo Kasipul": "Homa Bay",
  Karachuonyo: "Homa Bay",
  Rangwe: "Homa Bay",
  "Homa Bay Town": "Homa Bay",
  Ndhiwa: "Homa Bay",
  "Suba North": "Homa Bay",
  "Suba South": "Homa Bay",
  // Migori
  Rongo: "Migori",
  Awendo: "Migori",
  "Suna East": "Migori",
  "Suna West": "Migori",
  Uriri: "Migori",
  Nyatike: "Migori",
  "Kuria West": "Migori",
  "Kuria East": "Migori",
  // Kisii
  Bonchari: "Kisii",
  "South Mugirango": "Kisii",
  "Bomachoge Borabu": "Kisii",
  "Bomachoge Chache": "Kisii",
  Bobasi: "Kisii",
  "Nyaribari Masaba": "Kisii",
  "Nyaribari Chache": "Kisii",
  "Kitutu Chache North": "Kisii",
  "Kitutu Chache South": "Kisii",
  // Nyamira
  "Kitutu Masaba": "Nyamira",
  "West Mugirango": "Nyamira",
  "North Mugirango": "Nyamira",
  Borabu: "Nyamira",
  // Nairobi City
  "Dagoretti North": "Nairobi City",
  Westlands: "Nairobi City",
  "Dagoretti South": "Nairobi City",
  "Lang'ata": "Nairobi City",
  Kibra: "Nairobi City",
  Roysambu: "Nairobi City",
  Kasarani: "Nairobi City",
  Ruaraka: "Nairobi City",
  "Embakasi South": "Nairobi City",
  "Embakasi North": "Nairobi City",
  "Embakasi Central": "Nairobi City",
  "Embakasi East": "Nairobi City",
  "Embakasi West": "Nairobi City",
  Makadara: "Nairobi City",
  Kamukunji: "Nairobi City",
  Starehe: "Nairobi City",
  Mathare: "Nairobi City",
};

export const KENYA_COUNTIES = new Set([
  "Mombasa",
  "Kwale",
  "Kilifi",
  "Tana River",
  "Lamu",
  "Taita Taveta",
  "Garissa",
  "Wajir",
  "Mandera",
  "Marsabit",
  "Isiolo",
  "Meru",
  "Tharaka-Nithi",
  "Embu",
  "Kitui",
  "Machakos",
  "Makueni",
  "Nyandarua",
  "Nyeri",
  "Kirinyaga",
  "Murang'a",
  "Kiambu",
  "Turkana",
  "West Pokot",
  "Samburu",
  "Trans Nzoia",
  "Uasin Gishu",
  "Elgeyo Marakwet",
  "Nandi",
  "Baringo",
  "Laikipia",
  "Nakuru",
  "Narok",
  "Kajiado",
  "Kericho",
  "Bomet",
  "Kakamega",
  "Vihiga",
  "Bungoma",
  "Busia",
  "Siaya",
  "Kisumu",
  "Homa Bay",
  "Migori",
  "Kisii",
  "Nyamira",
  "Nairobi City",
  "Nairobi",
]);
